# <center>Machine Learning Project</center>

** **
## <center>*03 - Base Model Notebook*</center>

** **

Description of the notebook

Simple Model with evaluation


The members of the `team` are:
- Ana Farinha - 20211514
- Francisco Capontes - 20211692
- Maria Cruz - 20230760
- Sofia Gomes - 20240848
- Tahiya Laboni - 20240943

In [7]:
# Import libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix

In [8]:
# Import dataset
df = pd.read_csv('./project_data/train_data.csv')
df

C:\Users\Utilizador\AppData\Local\Temp\ipykernel_16172\1134853745.py:2: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('./project_data/train_data.csv')


Accident Date  Age at Injury Alternative Dispute Resolution  \
0         2019-12-30           31.0                              N   
1         2019-08-30           46.0                              N   
2         2019-12-06           40.0                              N   
3                NaN            NaN                            NaN   
4         2019-12-30           61.0                              N   
...              ...            ...                            ...   
593466           NaN            NaN                            NaN   
593467    2022-12-13           72.0                              N   
593468           NaN            NaN                            NaN   
593469           NaN            NaN                            NaN   
593470           NaN            NaN                            NaN   

       Assembly Date Attorney/Representative  Average Weekly Wage  Birth Year  \
0         2020-01-01                       N                 0.00      1988.0   
1         2020-01-01                       Y              1745.93      1973.0   
2         2020-01-01                       N              1434.80      1979.0   
3         2020-01-01                     NaN                  NaN         NaN   
4         2020-01-01                       N                  NaN      1958.0   
...              ...                     ...                  ...         ...   
593466    2022-12-31                     NaN                  NaN         NaN   
593467    2022-12-31                       N                 0.00      1950.0   
593468    2022-12-31                     NaN                  NaN         NaN   
593469    2022-12-31                     NaN                  NaN         NaN   
593470    2022-12-31                     NaN                  NaN         NaN   

          C-2 Date    C-3 Date                   Carrier Name  ...  \
0       2019-12-31         NaN     NEW HAMPSHIRE INSURANCE CO  ...   
1       2020-01-01  2020-01-14   ZURICH AMERICAN INSURANCE CO  ...   
2       2020-01-01         NaN      INDEMNITY INSURANCE CO OF  ...   
3              NaN         NaN                            NaN  ...   
4       2019-12-31         NaN           STATE INSURANCE FUND  ...   
...            ...         ...                            ...  ...   
593466         NaN         NaN                            NaN  ...   
593467  2022-12-31         NaN  TECHNOLOGY INSURANCE CO. INC.  ...   
593468         NaN         NaN                            NaN  ...   
593469         NaN         NaN                            NaN  ...   
593470         NaN         NaN                            NaN  ...   

       WCIO Cause of Injury Code  WCIO Cause of Injury Description  \
0                           27.0      FROM LIQUID OR GREASE SPILLS   
1                           97.0                 REPETITIVE MOTION   
2                           79.0    OBJECT BEING LIFTED OR HANDLED   
3                            NaN                               NaN   
4                           16.0   HAND TOOL, UTENSIL; NOT POWERED   
...                          ...                               ...   
593466                       NaN                               NaN   
593467                      25.0  FROM DIFFERENT LEVEL (ELEVATION)   
593468                       NaN                               NaN   
593469                       NaN                               NaN   
593470                       NaN                               NaN   

       WCIO Nature of Injury Code WCIO Nature of Injury Description  \
0                            10.0                         CONTUSION   
1                            49.0                    SPRAIN OR TEAR   
2                             7.0                        CONCUSSION   
3                             NaN                               NaN   
4                            43.0                          PUNCTURE   
...                           ...                               ...   
593466        

In [9]:
# Remove the na to make the visualization possible
df = df.dropna(subset=['Claim Injury Type'])

In [10]:
# Encode the target variable
label_encoder = LabelEncoder()
df['Claim Injury Type Encoded'] = label_encoder.fit_transform(df['Claim Injury Type'])

C:\Users\Utilizador\AppData\Local\Temp\ipykernel_16172\1942064479.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Claim Injury Type Encoded'] = label_encoder.fit_transform(df['Claim Injury Type'])


In [11]:
# Define features and target
X = df[['Age at Injury', 'Average Weekly Wage', 'Birth Year', 'Claim Identifier', 'IME-4 Count', 'Industry Code', 'WCIO Cause of Injury Code', 'WCIO Nature of Injury Code','WCIO Part Of Body Code', 'Agreement Reached', 'Number of Dependents']]
y = df['Claim Injury Type Encoded']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
# Initialize and train the Random Forest classifier
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))


Confusion Matrix:
[[  790  1611    32    18     1     0     0     0]
 [  567 57069   608   153    21     0     0     0]
 [    8  7861   785  4517   577     1     0     0]
 [    4   731   347 26744  1848     6     0     2]
 [    0   114   104  4115  5250     2     0     0]
 [    0     4    11   664   133     3     0     0]
 [    0     0     0    14     0     0     0     0]
 [    0    15     2    71     1     0     0     2]]

Classification Report:
                 precision    recall  f1-score   support

   1. CANCELLED       0.58      0.32      0.41      2452
    2. NON-COMP       0.85      0.98      0.91     58418
    3. MED ONLY       0.42      0.06      0.10     13749
   4. TEMPORARY       0.74      0.90      0.81     29682
5. PPD SCH LOSS       0.67      0.55      0.60      9585
     6. PPD NSL       0.25      0.00      0.01       815
         7. PTD       0.00      0.00      0.00        14
       8. DEATH       0.50      0.02      0.04        91

       accuracy                   

c:\Users\Utilizador\anaconda3\envs\ML_Project\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Utilizador\anaconda3\envs\ML_Project\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Utilizador\anaconda3\envs\ML_Project\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitaliz

In [13]:
# Import dataset
test_df = pd.read_csv('./project_data/train_data.csv')
test_df

C:\Users\Utilizador\AppData\Local\Temp\ipykernel_16172\347081480.py:2: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  test_df = pd.read_csv('./project_data/train_data.csv')


Accident Date  Age at Injury Alternative Dispute Resolution  \
0         2019-12-30           31.0                              N   
1         2019-08-30           46.0                              N   
2         2019-12-06           40.0                              N   
3                NaN            NaN                            NaN   
4         2019-12-30           61.0                              N   
...              ...            ...                            ...   
593466           NaN            NaN                            NaN   
593467    2022-12-13           72.0                              N   
593468           NaN            NaN                            NaN   
593469           NaN            NaN                            NaN   
593470           NaN            NaN                            NaN   

       Assembly Date Attorney/Representative  Average Weekly Wage  Birth Year  \
0         2020-01-01                       N                 0.00      1988.0   
1         2020-01-01                       Y              1745.93      1973.0   
2         2020-01-01                       N              1434.80      1979.0   
3         2020-01-01                     NaN                  NaN         NaN   
4         2020-01-01                       N                  NaN      1958.0   
...              ...                     ...                  ...         ...   
593466    2022-12-31                     NaN                  NaN         NaN   
593467    2022-12-31                       N                 0.00      1950.0   
593468    2022-12-31                     NaN                  NaN         NaN   
593469    2022-12-31                     NaN                  NaN         NaN   
593470    2022-12-31                     NaN                  NaN         NaN   

          C-2 Date    C-3 Date                   Carrier Name  ...  \
0       2019-12-31         NaN     NEW HAMPSHIRE INSURANCE CO  ...   
1       2020-01-01  2020-01-14   ZURICH AMERICAN INSURANCE CO  ...   
2       2020-01-01         NaN      INDEMNITY INSURANCE CO OF  ...   
3              NaN         NaN                            NaN  ...   
4       2019-12-31         NaN           STATE INSURANCE FUND  ...   
...            ...         ...                            ...  ...   
593466         NaN         NaN                            NaN  ...   
593467  2022-12-31         NaN  TECHNOLOGY INSURANCE CO. INC.  ...   
593468         NaN         NaN                            NaN  ...   
593469         NaN         NaN                            NaN  ...   
593470         NaN         NaN                            NaN  ...   

       WCIO Cause of Injury Code  WCIO Cause of Injury Description  \
0                           27.0      FROM LIQUID OR GREASE SPILLS   
1                           97.0                 REPETITIVE MOTION   
2                           79.0    OBJECT BEING LIFTED OR HANDLED   
3                            NaN                               NaN   
4                           16.0   HAND TOOL, UTENSIL; NOT POWERED   
...                          ...                               ...   
593466                       NaN                               NaN   
593467                      25.0  FROM DIFFERENT LEVEL (ELEVATION)   
593468                       NaN                               NaN   
593469                       NaN                               NaN   
593470                       NaN                               NaN   

       WCIO Nature of Injury Code WCIO Nature of Injury Description  \
0                            10.0                         CONTUSION   
1                            49.0                    SPRAIN OR TEAR   
2                             7.0                        CONCUSSION   
3                             NaN                               NaN   
4                            43.0                          PUNCTURE   
...                           ...                               ...   
593466        

In [15]:
# Make predictions
y_pred = model.predict(test_df[['Age at Injury', 'Average Weekly Wage', 'Birth Year', 'Claim Identifier', 'IME-4 Count', 'Industry Code', 'WCIO Cause of Injury Code', 'WCIO Nature of Injury Code','WCIO Part Of Body Code', 'Agreement Reached', 'Number of Dependents']])

In [19]:
y_pred = label_encoder.inverse_transform(y_pred)

In [17]:
test_id = test_df['Claim Identifier']

In [21]:
submission_df = pd.DataFrame({
    'Claim Identifier': test_id,
    'Claim Injury Type': y_pred
})

In [26]:
# Save the DataFrame to a CSV file
submission_df.to_csv('./submissions/Group49_Version01.csv', index=False)