# <center>Machine Learning Project</center>

** **
## <center>*03 - Base Model Notebook*</center>

** **

Description of the notebook

Simple Model with evaluation


The members of the `team` are:
- Ana Farinha - 20211514
- Francisco Capontes - 20211692
- Sofia Gomes - 20240848
- Rui Lourenço - 2021639


## <span style="color:salmon"> Table of Contents </span>

<a class="anchor" id="top"></a>

1. [Importing Libraries & Data](#one-bullet) 

2. [Prepare Dataset](#two-bullet)

   2.1 [Separate Target](#two-one-bullet) 

   2.2 [Train Validation Split](#two-two-bullet)
   
   2.3 [Impute Missing Values](#two-three-bullet) 
   
   2.4 [Scaling Data](#two-four-bullet) <br><br>

3. [Model Training](#three-bullet)

4. [Model Evaluation](#four-bullet) 

   4.1 [Training Evaluation](#four-one-bullet) 
   
   4.2 [Validation Evaluation](#four-two-bullet) <br><br>

5. [Test Prediction](#five-bullet) 

<a class="anchor" id="one-bullet"> 
    
# <span style="color:salmon"> 1. Importing Libraries & Data </span> 
</a>    
</div>

<a href="#top">Top &#129033;</a>

In [1]:
# Import libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

from utils import *

In [2]:
# Import  for training and validation
df = pd.read_csv('./preprocessed_data/train_data.csv', index_col = 'Claim Identifier')
df

Accident Date  Age at Injury  Average Weekly Wage  \
Claim Identifier                                                     
5393875             2019-12-30           31.0                  NaN   
5393091             2019-08-30           46.0              1745.93   
5393889             2019-12-06           40.0              1434.80   
5393887             2019-12-30           61.0                  NaN   
5393863             2019-12-26           67.0                  NaN   
...                        ...            ...                  ...   
6165265             2022-12-14           35.0                  NaN   
6165285             2022-12-15           33.0                  NaN   
6165506             2022-12-13           61.0               991.08   
6165339             2022-12-14           24.0                  NaN   
6165075             2022-12-13           72.0                  NaN   

                  Birth Year  IME-4 Count  WCIO Cause of Injury Code  \
Claim Identifier                                                       
5393875               1988.0          0.0                       27.0   
5393091               1973.0          4.0                       97.0   
5393889               1979.0          0.0                       79.0   
5393887               1958.0          0.0                       16.0   
5393863               1952.0          0.0                       31.0   
...                      ...          ...                        ...   
6165265               1987.0          0.0                       45.0   
6165285               1989.0          0.0                       74.0   
6165506               1961.0          1.0                       98.0   
6165339               1998.0          0.0                       59.0   
6165075               1950.0          0.0                       25.0   

                  WCIO Nature of Injury Code  WCIO Part Of Body Code  \
Claim Identifier                                                       
5393875                                 10.0                    62.0   
5393091                                 49.0                    38.0   
5393889                                  7.0                    10.0   
5393887                                 43.0                    36.0   
5393863                                 10.0                    38.0   
...                                      ...                     ...   
6165265                                 10.0                    42.0   
6165285                                 37.0                    35.0   
6165506                                 80.0                    34.0   
6165339                                 59.0                    55.0   
6165075                                 90.0                    -9.0   

                  Number of Dependents  Known Accident Date  ...  \
Claim Identifier                                             ...   
5393875                            1.0                    1  ...   
5393091                            4.0                    1  ...   
5393889                            6.0                    1  ...   
5393887                            1.0                    1  ...   
5393863                            5.0                    1  ...   
...                                ...                  ...  ...   
6165265                            4.0                    1  ...   
6165285                            6.0                    1  ...   
6165506                            3.0                    1  ...   
6165339                            5.0                    1  ...   
6165075                            3.0                    1  ...   

                  Zip_Code_Hash_13  Zip_Code_Hash_14  Zip_Code_Hash_15  \
Claim Identifier                                                         
5393875                        0.0               0.0               0.0   
5393091                        0.0              -1.0               0.0   
5393889                        0.0               0.

In [3]:
# Import dataset
test_df = pd.read_csv('./preprocessed_data/test_data.csv', index_col = 'Claim Identifier')
test_df

Accident Date  Age at Injury  Average Weekly Wage  \
Claim Identifier                                                     
6165911             2022-12-24           19.0                  NaN   
6166141             2022-11-20           19.0                  NaN   
6165907             2022-12-26           59.0                  NaN   
6166047             2022-12-28           55.0                  NaN   
6166102             2022-12-20           25.0                  NaN   
...                        ...            ...                  ...   
6553137             2012-09-12           52.0                  NaN   
6553119             2024-05-22           59.0                  NaN   
6553542             2024-05-06           45.0                  NaN   
6553455             2024-02-24           42.0                  NaN   
6553594             2024-06-05            NaN                  NaN   

                  Birth Year  IME-4 Count  WCIO Cause of Injury Code  \
Claim Identifier                                                       
6165911               2003.0          0.0                       31.0   
6166141               2003.0          0.0                       75.0   
6165907               1963.0          0.0                       68.0   
6166047               1967.0          0.0                       25.0   
6166102               1997.0          0.0                       79.0   
...                      ...          ...                        ...   
6553137               1960.0          0.0                        NaN   
6553119               1965.0          0.0                        NaN   
6553542               1979.0          0.0                        NaN   
6553455               1981.0          0.0                        NaN   
6553594                  NaN          0.0                        NaN   

                  WCIO Nature of Injury Code  WCIO Part Of Body Code  \
Claim Identifier                                                       
6165911                                 10.0                    54.0   
6166141                                 10.0                    10.0   
6165907                                 49.0                    62.0   
6166047                                 10.0                    53.0   
6166102                                 40.0                    37.0   
...                                      ...                     ...   
6553137                                  NaN                     NaN   
6553119                                  NaN                     NaN   
6553542                                  NaN                     NaN   
6553455                                  NaN                     NaN   
6553594                                  NaN                     NaN   

                  Number of Dependents  Known Accident Date  ...  \
Claim Identifier                                             ...   
6165911                              1                    1  ...   
6166141                              1                    1  ...   
6165907                              0                    1  ...   
6166047                              6                    1  ...   
6166102                              5                    1  ...   
...                                ...                  ...  ...   
6553137                              5                    1  ...   
6553119                              1                    1  ...   
6553542                              5                    1  ...   
6553455                              5                    1  ...   
6553594                              5                    1  ...   

                  Zip_Code_Hash_12  Zip_Code_Hash_13  Zip_Code_Hash_14  \
Claim Identifier                                                         
6165911                        0.0               0.0               0.0   
6166141                        0.0               0.0               0.0   
6165907                        0.0               0.

<a class="anchor" id="two-bullet"> 
    
# <span style="color:salmon"> 2. Prepare Dataset </span> 
</a>    
</div>
<a href="#top">Top &#129033;</a>

<a class="anchor" id="two-one-bullet"> 
    
## <span style="color:salmon"> 2.1 Separate Target </span> 
</a>    
</div>

In [4]:
# Define features and target
X = df.drop('Claim Injury Type Encoded', axis=1)
y = df['Claim Injury Type Encoded']

<a class="anchor" id="two-twpo-bullet"> 
    
## <span style="color:salmon"> 2.2 Train Validation Split </span> 
</a>    
</div>

In [5]:
# Split the data into training and testing sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
X_test = test_df.copy()

<a class="anchor" id="two-three-bullet"> 
    
## <span style="color:salmon"> 2.3 Impute Missing Values </span> 
</a>    
</div>

*Check missing values in each dataset*

In [7]:
X_train.isna().sum().sort_values()[X_train.isna().sum() != 0]

Birth Year                      1758
Age at Injury                   1758
WCIO Cause of Injury Code      12634
WCIO Nature of Injury Code     12644
WCIO Part Of Body Code         13793
Average Weekly Wage           291230
dtype: int64

In [8]:
X_val.isna().sum().sort_values()[X_val.isna().sum() != 0]

Birth Year                      428
Age at Injury                   428
WCIO Cause of Injury Code      3004
WCIO Nature of Injury Code     3011
WCIO Part Of Body Code         3287
Average Weekly Wage           72869
dtype: int64

In [9]:
X_test.isna().sum().sort_values()[X_test.isna().sum() != 0]

Birth Year                       982
Age at Injury                    982
WCIO Part Of Body Code          9549
WCIO Cause of Injury Code      10348
WCIO Nature of Injury Code     10560
Average Weekly Wage           335753
dtype: int64

*Input `Average Weekly Wage` and variables created from it*

In [10]:
median_avg_week_wage = X_train['Average Weekly Wage'].median()

X_train['Average Weekly Wage'] = X_train['Average Weekly Wage'].fillna(median_avg_week_wage)
X_val['Average Weekly Wage'] = X_val['Average Weekly Wage'].fillna(median_avg_week_wage)
X_test['Average Weekly Wage'] = X_test['Average Weekly Wage'].fillna(median_avg_week_wage)

In [11]:
financial_impact(X_train)
financial_impact(X_val)
financial_impact(X_test)

*Input `Age at Injury` and variables that can be calculated with it*

In [12]:
median_age_at_injury = X_train['Age at Injury'].median()

X_train['Age at Injury'] = X_train['Age at Injury'].fillna(median_age_at_injury)
X_val['Age at Injury'] = X_val['Age at Injury'].fillna(median_age_at_injury)
X_test['Age at Injury'] = X_test['Age at Injury'].fillna(median_age_at_injury)

In [13]:
def calculate_birth_year(df):
    # Ensure the correct format of 'Birth Year'
    df['Accident Date'] = pd.to_datetime(df['Accident Date'], errors='coerce')

    # Filter the rows where 'Birth Year' is NaN, but 'Age at Injury' and 'Accident Date' are not NaN
    condition = df['Birth Year'].isna() & df['Age at Injury'].notna() & df['Accident Date'].notna()

    # Replace missing 'Birth Year' with the difference between 'Accident Date' year and 'Age at Injury'
    df.loc[condition, 'Birth Year'] = df.loc[condition, 'Accident Date'].dt.year - df.loc[condition, 'Age at Injury']

In [14]:
calculate_birth_year(X_train)
calculate_birth_year(X_val)
calculate_birth_year(X_test)

*Drop Dates*

In [15]:
X_train.drop('Accident Date', axis=1, inplace=True)
X_val.drop('Accident Date', axis=1, inplace=True)
X_test.drop('Accident Date', axis=1, inplace=True)

<a class="anchor" id="two-four-bullet"> 
    
## <span style="color:salmon"> 2.4 Scaling Data </span> 
</a>    
</div>

In [16]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

<a class="anchor" id="three-bullet"> 
    
# <span style="color:salmon"> 3. Model Training </span> 
</a>    
</div>

<a href="#top">Top &#129033;</a>

In [17]:
class_mapping = {
    0:'1. CANCELLED', 
    1:'2. NON-COMP',
    2:'3. MED ONLY', 
    3:'4. TEMPORARY',
    4:'5. PPD SCH LOSS', 
    5:'6. PPD NSL', 
    6:'7. PTD', 
    7:'8. DEATH'
}

# Use the values from class_mapping as the target names
target_names = list(class_mapping.values())

In [18]:
# Initialize and train the DecisionTreeClassifier
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

<a class="anchor" id="four-bullet"> 
    
# <span style="color:salmon"> 4. Model Evaluation </span> 
</a>    
</div>
<a href="#top">Top &#129033;</a>

<a class="anchor" id="four-one-bullet"> 
    
## <span style="color:salmon"> 4.1 Training Evaluation </span> 
</a>    
</div>

In [19]:
# Make training predictions
y_train_pred = model.predict(X_train)

In [20]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_train, y_train_pred))
print("\nClassification Report:")
print(classification_report(y_train, y_train_pred, target_names=target_names))


Confusion Matrix:
[[ 10011      2      0      0      0      0      0      0]
 [     5 232933      3      4      0      0      0      0]
 [     0      2  55040      2      2      0      0      0]
 [     0      3      2 118638      1      1      0      0]
 [     0      0      0      0  38738      0      0      0]
 [     0      0      1      0      0   3383      0      0]
 [     0      0      0      0      0      0     78      0]
 [     0      0      0      0      0      0      0    370]]

Classification Report:
                 precision    recall  f1-score   support

   1. CANCELLED       1.00      1.00      1.00     10013
    2. NON-COMP       1.00      1.00      1.00    232945
    3. MED ONLY       1.00      1.00      1.00     55046
   4. TEMPORARY       1.00      1.00      1.00    118645
5. PPD SCH LOSS       1.00      1.00      1.00     38738
     6. PPD NSL       1.00      1.00      1.00      3384
         7. PTD       1.00      1.00      1.00        78
       8. DEATH       1.00  

<a class="anchor" id="four-two-bullet"> 
    
## <span style="color:salmon"> 4.2 Validation Evaluation </span> 
</a>    
</div>

In [21]:
# Make validation predictions
y_val_pred = model.predict(X_val)


In [22]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))
print("\nClassification Report:")
print(classification_report(y_val, y_val_pred, target_names=target_names))


Confusion Matrix:
[[  935  1255   155   109     7     1     0     0]
 [ 1317 48671  6470  1492   165     8     0    10]
 [  176  5891  3009  3706   960    99     1    18]
 [  114  1466  4024 19900  3747   574     9    28]
 [   13   160   958  3499  4735   166     2     9]
 [    1     9    73   502   186    54     2     0]
 [    0     0     2    11     5     0     1     0]
 [    3    11    16    48     9     2     0    11]]

Classification Report:
                 precision    recall  f1-score   support

   1. CANCELLED       0.37      0.38      0.37      2462
    2. NON-COMP       0.85      0.84      0.84     58133
    3. MED ONLY       0.20      0.22      0.21     13860
   4. TEMPORARY       0.68      0.67      0.67     29862
5. PPD SCH LOSS       0.48      0.50      0.49      9542
     6. PPD NSL       0.06      0.07      0.06       827
         7. PTD       0.07      0.05      0.06        19
       8. DEATH       0.14      0.11      0.12       100

       accuracy                   

<a class="anchor" id="five-bullet"> 
    
# <span style="color:salmon"> 5. Test Predictions </span> 
</a>    
</div>

<a href="#top">Top &#129033;</a>

In [23]:
# Make validation predictions
y_test_pred = model.predict(X_test)

In [24]:
test_id = test_df.index

In [25]:
submission_df = pd.DataFrame({
    'Claim Identifier': test_id,
    'Claim Injury Type': y_test_pred
})

In [26]:
# Save the DataFrame to a CSV file
submission_df.to_csv('./submissions/Group49_Version04.csv', index=False)