# <center>Machine Learning Project</center>

** **
## <center>*05 - Logistic Regression*</center>

** **

The members of the `team` are:
- Ana Farinha - 20211514
- Francisco Capontes - 20211692
- Sofia Gomes - 20240848
- Rui Lourenço - 2021639



In [92]:
# Import libraries
import pandas as pd
import numpy as np

#make the split here
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score

from utils import *

## <span style="color:salmon"> 1. Import Dataset </span> 

In [93]:
# Import dataset
df = pd.read_csv('preprocessed_data/train_data.csv', index_col="Claim Identifier")
df

Accident Date  Age at Injury  Average Weekly Wage  \
Claim Identifier                                                     
5393875             2019-12-30           31.0                  NaN   
5393091             2019-08-30           46.0              1745.93   
5393889             2019-12-06           40.0              1434.80   
5393887             2019-12-30           61.0                  NaN   
5393863             2019-12-26           67.0                  NaN   
...                        ...            ...                  ...   
6165265             2022-12-14           35.0                  NaN   
6165285             2022-12-15           33.0                  NaN   
6165506             2022-12-13           61.0               991.08   
6165339             2022-12-14           24.0                  NaN   
6165075             2022-12-13           72.0                  NaN   

                  Birth Year  IME-4 Count  WCIO Cause of Injury Code  \
Claim Identifier                                                       
5393875               1988.0          0.0                       27.0   
5393091               1973.0          4.0                       97.0   
5393889               1979.0          0.0                       79.0   
5393887               1958.0          0.0                       16.0   
5393863               1952.0          0.0                       31.0   
...                      ...          ...                        ...   
6165265               1987.0          0.0                       45.0   
6165285               1989.0          0.0                       74.0   
6165506               1961.0          1.0                       98.0   
6165339               1998.0          0.0                       59.0   
6165075               1950.0          0.0                       25.0   

                  WCIO Nature of Injury Code  WCIO Part Of Body Code  \
Claim Identifier                                                       
5393875                                 10.0                    62.0   
5393091                                 49.0                    38.0   
5393889                                  7.0                    10.0   
5393887                                 43.0                    36.0   
5393863                                 10.0                    38.0   
...                                      ...                     ...   
6165265                                 10.0                    42.0   
6165285                                 37.0                    35.0   
6165506                                 80.0                    34.0   
6165339                                 59.0                    55.0   
6165075                                 90.0                    -9.0   

                  Number of Dependents  Known Accident Date  ...  \
Claim Identifier                                             ...   
5393875                            1.0                    1  ...   
5393091                            4.0                    1  ...   
5393889                            6.0                    1  ...   
5393887                            1.0                    1  ...   
5393863                            5.0                    1  ...   
...                                ...                  ...  ...   
6165265                            4.0                    1  ...   
6165285                            6.0                    1  ...   
6165506                            3.0                    1  ...   
6165339                            5.0                    1  ...   
6165075                            3.0                    1  ...   

                  Zip_Code_Hash_13  Zip_Code_Hash_14  Zip_Code_Hash_15  \
Claim Identifier                                                         
5393875                        0.0               0.0               0.0   
5393091                        0.0              -1.0               0.0   
5393889                        0.0               0.

In [94]:
# Import dataset
test_df = pd.read_csv('./preprocessed_data/test_data.csv', index_col = 'Claim Identifier')
test_df

Accident Date  Age at Injury  Average Weekly Wage  \
Claim Identifier                                                     
6165911             2022-12-24           19.0                  NaN   
6166141             2022-11-20           19.0                  NaN   
6165907             2022-12-26           59.0                  NaN   
6166047             2022-12-28           55.0                  NaN   
6166102             2022-12-20           25.0                  NaN   
...                        ...            ...                  ...   
6553137             2012-09-12           52.0                  NaN   
6553119             2024-05-22           59.0                  NaN   
6553542             2024-05-06           45.0                  NaN   
6553455             2024-02-24           42.0                  NaN   
6553594             2024-06-05            NaN                  NaN   

                  Birth Year  IME-4 Count  WCIO Cause of Injury Code  \
Claim Identifier                                                       
6165911               2003.0          0.0                       31.0   
6166141               2003.0          0.0                       75.0   
6165907               1963.0          0.0                       68.0   
6166047               1967.0          0.0                       25.0   
6166102               1997.0          0.0                       79.0   
...                      ...          ...                        ...   
6553137               1960.0          0.0                        NaN   
6553119               1965.0          0.0                        NaN   
6553542               1979.0          0.0                        NaN   
6553455               1981.0          0.0                        NaN   
6553594                  NaN          0.0                        NaN   

                  WCIO Nature of Injury Code  WCIO Part Of Body Code  \
Claim Identifier                                                       
6165911                                 10.0                    54.0   
6166141                                 10.0                    10.0   
6165907                                 49.0                    62.0   
6166047                                 10.0                    53.0   
6166102                                 40.0                    37.0   
...                                      ...                     ...   
6553137                                  NaN                     NaN   
6553119                                  NaN                     NaN   
6553542                                  NaN                     NaN   
6553455                                  NaN                     NaN   
6553594                                  NaN                     NaN   

                  Number of Dependents  Known Accident Date  ...  \
Claim Identifier                                             ...   
6165911                              1                    1  ...   
6166141                              1                    1  ...   
6165907                              0                    1  ...   
6166047                              6                    1  ...   
6166102                              5                    1  ...   
...                                ...                  ...  ...   
6553137                              5                    1  ...   
6553119                              1                    1  ...   
6553542                              5                    1  ...   
6553455                              5                    1  ...   
6553594                              5                    1  ...   

                  Zip_Code_Hash_12  Zip_Code_Hash_13  Zip_Code_Hash_14  \
Claim Identifier                                                         
6165911                        0.0               0.0               0.0   
6166141                        0.0               0.0               0.0   
6165907                        0.0               0.

## <span style="color:salmon"> 2. Prepare Dataset </span> 

Define y as a target "Claim Injury Type Encoded" and X with all the other columns

In [95]:
X = df.drop(["Claim Injury Type Encoded"], axis = 1)
y = df["Claim Injury Type Encoded"]

Split the data and the target to X_train, X_test, y_train, y_test, where test_size should be equal to 0.25, stratify equal to target and shuffle equal to True

In [96]:
X_train, X_val, y_train, y_val = train_test_split(X,y, test_size = 0.25, stratify = y, shuffle = True)

Define X_test

In [97]:
X_test = test_df.copy()

Check missing values in each dataset:

In [98]:
X_train.isna().sum().sort_values()[X_train.isna().sum() != 0]

Birth Year                      1659
Age at Injury                   1659
WCIO Cause of Injury Code      11753
WCIO Nature of Injury Code     11764
WCIO Part Of Body Code         12853
Average Weekly Wage           272979
dtype: int64

In [99]:
X_val.isna().sum().sort_values()[X_val.isna().sum() != 0]

Birth Year                      527
Age at Injury                   527
WCIO Cause of Injury Code      3885
WCIO Nature of Injury Code     3891
WCIO Part Of Body Code         4227
Average Weekly Wage           91120
dtype: int64

In [100]:
X_test.isna().sum().sort_values()[X_test.isna().sum() != 0]

Birth Year                       982
Age at Injury                    982
WCIO Part Of Body Code          9549
WCIO Cause of Injury Code      10348
WCIO Nature of Injury Code     10560
Average Weekly Wage           335753
dtype: int64

Input `Average Weekly Wage` and variables created from it

In [101]:
median_avg_week_wage = X_train['Average Weekly Wage'].median()

X_train['Average Weekly Wage'] = X_train['Average Weekly Wage'].fillna(median_avg_week_wage)
X_val['Average Weekly Wage'] = X_val['Average Weekly Wage'].fillna(median_avg_week_wage)
X_test['Average Weekly Wage'] = X_test['Average Weekly Wage'].fillna(median_avg_week_wage)

In [102]:
financial_impact(X_train)
financial_impact(X_val)
financial_impact(X_test)

*Input `Age at Injury` and variables that can be calculated with it*

In [103]:
median_age_at_injury = X_train['Age at Injury'].median()

X_train['Age at Injury'] = X_train['Age at Injury'].fillna(median_age_at_injury)
X_val['Age at Injury'] = X_val['Age at Injury'].fillna(median_age_at_injury)
X_test['Age at Injury'] = X_test['Age at Injury'].fillna(median_age_at_injury)

In [104]:
def calculate_birth_year(df):
    # Ensure the correct format of 'Birth Year'
    df['Accident Date'] = pd.to_datetime(df['Accident Date'], errors='coerce')

    # Filter the rows where 'Birth Year' is NaN, but 'Age at Injury' and 'Accident Date' are not NaN
    condition = df['Birth Year'].isna() & df['Age at Injury'].notna() & df['Accident Date'].notna()

    # Replace missing 'Birth Year' with the difference between 'Accident Date' year and 'Age at Injury'
    df.loc[condition, 'Birth Year'] = df.loc[condition, 'Accident Date'].dt.year - df.loc[condition, 'Age at Injury']

In [105]:
calculate_birth_year(X_train)
calculate_birth_year(X_val)
calculate_birth_year(X_test)

Drop the columns: Accident Date, WCIO Part Of Body Code, WCIO Cause of Injury Code and CIO Nature of Injury Code

In [106]:
X_train.drop('Accident Date', axis=1, inplace=True)
X_val.drop('Accident Date', axis=1, inplace=True)
X_test.drop('Accident Date', axis=1, inplace=True)

In [107]:
X_train.drop('WCIO Part Of Body Code', axis=1, inplace=True)
X_val.drop('WCIO Part Of Body Code', axis=1, inplace=True)
X_test.drop('WCIO Part Of Body Code', axis=1, inplace=True)

In [108]:
X_train.drop('WCIO Cause of Injury Code', axis=1, inplace=True)
X_val.drop('WCIO Cause of Injury Code', axis=1, inplace=True)
X_test.drop('WCIO Cause of Injury Code', axis=1, inplace=True)

In [109]:
X_train.drop('WCIO Nature of Injury Code', axis=1, inplace=True)
X_val.drop('WCIO Nature of Injury Code', axis=1, inplace=True)
X_test.drop('WCIO Nature of Injury Code', axis=1, inplace=True)

Scale the data:

In [110]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

## <span style="color:salmon"> 3. Logistic Regression </span> 

Applies Logistic Regression classifier:

In [111]:
model = LogisticRegression()

#### <span style="color:salmon"> 3.1 Fit the model to the train data </span> 

In [112]:
model.fit(X_train, y_train)

/opt/anaconda3/envs/ML2425/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

#### <span style="color:salmon"> 3.2 Predict the labels with model </span> 

Make training predictions:

In [ ]:
y_train_pred = model.predict(X_train)

Make val predictions:

In [114]:
y_val_pred = model.predict(X_val)

Predict Probability in training

In [115]:
pred_prob = model.predict_proba(X_train)
pred_prob

array([[1.19455262e-02, 6.07854812e-01, 1.40509150e-01, ...,
        8.77993580e-06, 8.91774585e-06, 1.56382848e-05],
       [2.59289990e-02, 8.80355400e-01, 5.02877518e-02, ...,
        9.21286506e-06, 9.60803968e-06, 7.90688104e-05],
       [1.62555058e-03, 1.02828634e-01, 2.74001345e-01, ...,
        5.60323383e-02, 6.87860970e-04, 5.25872577e-04],
       ...,
       [6.89143509e-03, 7.40614649e-01, 1.24059387e-01, ...,
        2.84100054e-05, 3.70116025e-05, 6.21376785e-05],
       [1.28590230e-02, 6.32578997e-01, 1.38050165e-01, ...,
        2.26533615e-05, 1.07450570e-05, 1.86337132e-05],
       [5.01843918e-03, 7.66497709e-01, 1.23347262e-01, ...,
        2.25893232e-05, 1.48920667e-05, 9.40868614e-05]])

Predict Probability in val

In [116]:
pred_prob = model.predict_proba(X_val)
pred_prob

array([[4.52827195e-03, 8.16263563e-01, 7.74407076e-02, ...,
        2.68645614e-05, 2.94064450e-05, 8.98421058e-06],
       [5.86174496e-03, 7.77305607e-01, 1.14421592e-01, ...,
        9.79620790e-06, 8.24924725e-06, 1.04391026e-04],
       [3.90902044e-03, 8.09289216e-01, 8.78248366e-02, ...,
        2.45517550e-05, 6.86527005e-05, 2.68910601e-05],
       ...,
       [7.42015362e-03, 5.91425657e-01, 1.45457048e-01, ...,
        1.82677506e-04, 7.51568806e-05, 4.00996540e-05],
       [1.06909126e-02, 7.39370876e-01, 8.91226906e-02, ...,
        3.94455569e-05, 4.46409293e-05, 1.83113783e-04],
       [2.70149445e-04, 2.70412051e-02, 1.13219763e-01, ...,
        3.56991132e-04, 1.08034050e-04, 3.48068080e-07]])

In [117]:
model.coef_

array([[ 3.92803854e-03, -5.28451061e-01,  4.03838556e-02,
        -2.13743552e+00,  1.57826518e-01,  0.00000000e+00,
         0.00000000e+00, -2.19736799e-01, -8.12743463e-02,
        -1.88416401e-01, -4.26603919e-02, -4.26603919e-02,
        -4.58755924e-01, -9.16655418e-02, -2.69750076e-02,
         8.69218204e-03,  4.30366303e-01,  1.68081417e-01,
        -5.28949162e-03,  3.41531077e-03, -2.24682449e-01,
        -5.63286509e-02, -1.35727112e-02,  2.14862512e-02,
        -8.06945504e-02,  7.33669390e-02,  1.50432704e-02,
        -2.28378913e-02, -1.89710431e-01, -5.63418805e-03,
        -1.54152603e-02,  3.24135120e-02, -1.27124562e-01,
        -4.91867380e-02,  2.91543456e-03,  4.17089171e-02,
        -1.09294888e-02,  8.29522594e-02,  8.45971212e-02,
         2.20154386e-01, -2.39302122e-01, -3.79804244e-01,
        -9.94480573e-02,  4.06423019e-02,  4.10413282e-02,
         3.03913913e-02,  8.40467372e-02,  3.68531160e-04,
        -6.07366097e-03, -2.36192285e-02,  8.26457025e-0

#### <span style="color:salmon"> 3.3 Evaluate the model </span> 

In [118]:
class_mapping = {
    0:'1. CANCELLED', 
    1:'2. NON-COMP',
    2:'3. MED ONLY', 
    3:'4. TEMPORARY',
    4:'5. PPD SCH LOSS', 
    5:'6. PPD NSL', 
    6:'7. PTD', 
    7:'8. DEATH'
}

# Use the values from class_mapping as the target names
target_names = list(class_mapping.values())

Compute confusion matrix to evaluate the accuracy of a classification

In [119]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_train, y_train_pred))
print("\nClassification Report:")
print(classification_report(y_train, y_train_pred, target_names=target_names))

Confusion Matrix:


[[  2094   6299     56    813     93      0      0      1]
 [  1544 205407    372  10029    949      0      0      7]
 [    73  34462    891  13951   2299      1      1      2]
 [    83  43669   1043  62586   3981      4      0     14]
 [    19   4116    441  21974   9659      1      0      0]
 [     0     20     29   2685    424      0      0      0]
 [     1      0      1     64      7      0      0      0]
 [     0    165      4    159      5      0      0     20]]

Classification Report:
                 precision    recall  f1-score   support

   1. CANCELLED       0.55      0.22      0.32      9356
    2. NON-COMP       0.70      0.94      0.80    218308
    3. MED ONLY       0.31      0.02      0.03     51680
   4. TEMPORARY       0.56      0.56      0.56    111380
5. PPD SCH LOSS       0.55      0.27      0.36     36210
     6. PPD NSL       0.00      0.00      0.00      3158
         7. PTD       0.00      0.00      0.00        73
       8. DEATH       0.45      0.06      0.10

In [120]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))
print("\nClassification Report:")
print(classification_report(y_val, y_val_pred, target_names=target_names))


Confusion Matrix:
[[  725  2061    17   292    23     0     0     1]
 [  461 68451   111  3439   305     0     0     3]
 [   32 11585   277  4535   795     0     0     2]
 [   32 14601   330 20711  1450     0     1     2]
 [    2  1446   161  7278  3183     0     0     0]
 [    0     2     4   903   144     0     0     0]
 [    0     0     0    16     8     0     0     0]
 [    0    53     2    52     4     0     0     6]]

Classification Report:


/opt/anaconda3/envs/ML2425/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


                 precision    recall  f1-score   support

   1. CANCELLED       0.58      0.23      0.33      3119
    2. NON-COMP       0.70      0.94      0.80     72770
    3. MED ONLY       0.31      0.02      0.03     17226
   4. TEMPORARY       0.56      0.56      0.56     37127
5. PPD SCH LOSS       0.54      0.26      0.35     12070
     6. PPD NSL       0.00      0.00      0.00      1053
         7. PTD       0.00      0.00      0.00        24
       8. DEATH       0.43      0.05      0.09       117

       accuracy                           0.65    143506
      macro avg       0.39      0.26      0.27    143506
   weighted avg       0.59      0.65      0.59    143506



/opt/anaconda3/envs/ML2425/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/envs/ML2425/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


##### <span style="color:salmon"> 3.3.1 The accuracy score </span> 

In [121]:
target_mode = y_train.mode()[0]
simple_predictions = np.array([target_mode for i in range(len(y_val))])
simple_predictions
accuracy_score(y_val, simple_predictions)

0.5070868117012529

In [122]:
accuracy = accuracy_score(y_val, y_val_pred)
accuracy

0.650516354716876

## <span style="color:salmon"> 4. Test Predictions </span> 

Make validation predictions:

In [ ]:
y_test_pred = model.predict(X_test)

In [ ]:
test_id = test_df.index

In [ ]:
submission_df = pd.DataFrame({
    'Claim Identifier': test_id,
    'Claim Injury Type': y_test_pred
})

In [ ]:
submission_df.to_csv('./submissions/Group49_logistic_model.csv', index=False)