# <center>Machine Learning Project</center>

** **
## <center>*03.3 - Logistic Regression*</center>

** **

The members of the `team` are:
- Ana Farinha - 20211514
- Francisco Capontes - 20211692
- Sofia Gomes - 20240848
- Rui Lourenço - 2021639



In [126]:
# Import libraries
import pandas as pd
import numpy as np

#make the split here
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score

from utils import *

## <span style="color:salmon"> 1. Import Dataset </span> 

In [127]:
# Import dataset
df = pd.read_csv('preprocessed_data/train_data.csv', index_col="Claim Identifier")
df

Accident Date  Age at Injury  Average Weekly Wage  \
Claim Identifier                                                     
5393875             2019-12-30           31.0                  NaN   
5393091             2019-08-30           46.0              1745.93   
5393889             2019-12-06           40.0              1434.80   
5393887             2019-12-30           61.0                  NaN   
5393863             2019-12-26           67.0                  NaN   
...                        ...            ...                  ...   
6165265             2022-12-14           35.0                  NaN   
6165285             2022-12-15           33.0                  NaN   
6165506             2022-12-13           61.0               991.08   
6165339             2022-12-14           24.0                  NaN   
6165075             2022-12-13           72.0                  NaN   

                  Birth Year  IME-4 Count  WCIO Cause of Injury Code  \
Claim Identifier                                                       
5393875               1988.0          0.0                       27.0   
5393091               1973.0          4.0                       97.0   
5393889               1979.0          0.0                       79.0   
5393887               1958.0          0.0                       16.0   
5393863               1952.0          0.0                       31.0   
...                      ...          ...                        ...   
6165265               1987.0          0.0                       45.0   
6165285               1989.0          0.0                       74.0   
6165506               1961.0          1.0                       98.0   
6165339               1998.0          0.0                       59.0   
6165075               1950.0          0.0                       25.0   

                  WCIO Nature of Injury Code  WCIO Part Of Body Code  \
Claim Identifier                                                       
5393875                                 10.0                    62.0   
5393091                                 49.0                    38.0   
5393889                                  7.0                    10.0   
5393887                                 43.0                    36.0   
5393863                                 10.0                    38.0   
...                                      ...                     ...   
6165265                                 10.0                    42.0   
6165285                                 37.0                    35.0   
6165506                                 80.0                    34.0   
6165339                                 59.0                    55.0   
6165075                                 90.0                    -9.0   

                  Number of Dependents  Known Accident Date  ...  \
Claim Identifier                                             ...   
5393875                            1.0                    1  ...   
5393091                            4.0                    1  ...   
5393889                            6.0                    1  ...   
5393887                            1.0                    1  ...   
5393863                            5.0                    1  ...   
...                                ...                  ...  ...   
6165265                            4.0                    1  ...   
6165285                            6.0                    1  ...   
6165506                            3.0                    1  ...   
6165339                            5.0                    1  ...   
6165075                            3.0                    1  ...   

                  Zip_Code_Hash_13  Zip_Code_Hash_14  Zip_Code_Hash_15  \
Claim Identifier                                                         
5393875                        0.0               0.0               0.0   
5393091                        0.0              -1.0               0.0   
5393889                        0.0               0.

In [128]:
# Import dataset
test_df = pd.read_csv('./preprocessed_data/test_data.csv', index_col = 'Claim Identifier')
test_df

Accident Date  Age at Injury  Average Weekly Wage  \
Claim Identifier                                                     
6165911             2022-12-24           19.0                  NaN   
6166141             2022-11-20           19.0                  NaN   
6165907             2022-12-26           59.0                  NaN   
6166047             2022-12-28           55.0                  NaN   
6166102             2022-12-20           25.0                  NaN   
...                        ...            ...                  ...   
6553137             2012-09-12           52.0                  NaN   
6553119             2024-05-22           59.0                  NaN   
6553542             2024-05-06           45.0                  NaN   
6553455             2024-02-24           42.0                  NaN   
6553594             2024-06-05            NaN                  NaN   

                  Birth Year  IME-4 Count  WCIO Cause of Injury Code  \
Claim Identifier                                                       
6165911               2003.0          0.0                       31.0   
6166141               2003.0          0.0                       75.0   
6165907               1963.0          0.0                       68.0   
6166047               1967.0          0.0                       25.0   
6166102               1997.0          0.0                       79.0   
...                      ...          ...                        ...   
6553137               1960.0          0.0                        NaN   
6553119               1965.0          0.0                        NaN   
6553542               1979.0          0.0                        NaN   
6553455               1981.0          0.0                        NaN   
6553594                  NaN          0.0                        NaN   

                  WCIO Nature of Injury Code  WCIO Part Of Body Code  \
Claim Identifier                                                       
6165911                                 10.0                    54.0   
6166141                                 10.0                    10.0   
6165907                                 49.0                    62.0   
6166047                                 10.0                    53.0   
6166102                                 40.0                    37.0   
...                                      ...                     ...   
6553137                                  NaN                     NaN   
6553119                                  NaN                     NaN   
6553542                                  NaN                     NaN   
6553455                                  NaN                     NaN   
6553594                                  NaN                     NaN   

                  Number of Dependents  Known Accident Date  ...  \
Claim Identifier                                             ...   
6165911                              1                    1  ...   
6166141                              1                    1  ...   
6165907                              0                    1  ...   
6166047                              6                    1  ...   
6166102                              5                    1  ...   
...                                ...                  ...  ...   
6553137                              5                    1  ...   
6553119                              1                    1  ...   
6553542                              5                    1  ...   
6553455                              5                    1  ...   
6553594                              5                    1  ...   

                  Zip_Code_Hash_12  Zip_Code_Hash_13  Zip_Code_Hash_14  \
Claim Identifier                                                         
6165911                        0.0               0.0               0.0   
6166141                        0.0               0.0               0.0   
6165907                        0.0               0.

## <span style="color:salmon"> 2. Prepare Dataset </span> 

Define y as a target "Claim Injury Type Encoded" and X with all the other columns

In [129]:
X = df.drop(["Claim Injury Type Encoded"], axis = 1)
y = df["Claim Injury Type Encoded"]

Split the data and the target to X_train, X_test, y_train, y_test, where test_size should be equal to 0.25, stratify equal to target and shuffle equal to True

In [ ]:
X_train, X_val, y_train, y_val = train_test_split(X,y, test_size = 0.75, stratify = y, shuffle = True)

Define X_test

In [131]:
X_test = test_df.copy()

Check missing values in each dataset:

In [132]:
X_train.isna().sum().sort_values()[X_train.isna().sum() != 0]

Birth Year                      1649
Age at Injury                   1649
WCIO Cause of Injury Code      11680
WCIO Nature of Injury Code     11700
WCIO Part Of Body Code         12776
Average Weekly Wage           272969
dtype: int64

In [133]:
X_val.isna().sum().sort_values()[X_val.isna().sum() != 0]

Birth Year                      537
Age at Injury                   537
WCIO Nature of Injury Code     3955
WCIO Cause of Injury Code      3958
WCIO Part Of Body Code         4304
Average Weekly Wage           91130
dtype: int64

In [134]:
X_test.isna().sum().sort_values()[X_test.isna().sum() != 0]

Birth Year                       982
Age at Injury                    982
WCIO Part Of Body Code          9549
WCIO Cause of Injury Code      10348
WCIO Nature of Injury Code     10560
Average Weekly Wage           335753
dtype: int64

Input `Average Weekly Wage` and variables created from it

In [135]:
median_avg_week_wage = X_train['Average Weekly Wage'].median()

X_train['Average Weekly Wage'] = X_train['Average Weekly Wage'].fillna(median_avg_week_wage)
X_val['Average Weekly Wage'] = X_val['Average Weekly Wage'].fillna(median_avg_week_wage)
X_test['Average Weekly Wage'] = X_test['Average Weekly Wage'].fillna(median_avg_week_wage)

In [136]:
financial_impact(X_train)
financial_impact(X_val)
financial_impact(X_test)

*Input `Age at Injury` and variables that can be calculated with it*

In [137]:
median_age_at_injury = X_train['Age at Injury'].median()

X_train['Age at Injury'] = X_train['Age at Injury'].fillna(median_age_at_injury)
X_val['Age at Injury'] = X_val['Age at Injury'].fillna(median_age_at_injury)
X_test['Age at Injury'] = X_test['Age at Injury'].fillna(median_age_at_injury)

In [138]:
def calculate_birth_year(df):
    # Ensure the correct format of 'Birth Year'
    df['Accident Date'] = pd.to_datetime(df['Accident Date'], errors='coerce')

    # Filter the rows where 'Birth Year' is NaN, but 'Age at Injury' and 'Accident Date' are not NaN
    condition = df['Birth Year'].isna() & df['Age at Injury'].notna() & df['Accident Date'].notna()

    # Replace missing 'Birth Year' with the difference between 'Accident Date' year and 'Age at Injury'
    df.loc[condition, 'Birth Year'] = df.loc[condition, 'Accident Date'].dt.year - df.loc[condition, 'Age at Injury']

In [139]:
calculate_birth_year(X_train)
calculate_birth_year(X_val)
calculate_birth_year(X_test)

Drop the columns: Accident Date, WCIO Part Of Body Code, WCIO Cause of Injury Code and CIO Nature of Injury Code

In [140]:
X_train.drop('Accident Date', axis=1, inplace=True)
X_val.drop('Accident Date', axis=1, inplace=True)
X_test.drop('Accident Date', axis=1, inplace=True)

In [141]:
X_train.drop('WCIO Part Of Body Code', axis=1, inplace=True)
X_val.drop('WCIO Part Of Body Code', axis=1, inplace=True)
X_test.drop('WCIO Part Of Body Code', axis=1, inplace=True)

In [142]:
X_train.drop('WCIO Cause of Injury Code', axis=1, inplace=True)
X_val.drop('WCIO Cause of Injury Code', axis=1, inplace=True)
X_test.drop('WCIO Cause of Injury Code', axis=1, inplace=True)

In [143]:
X_train.drop('WCIO Nature of Injury Code', axis=1, inplace=True)
X_val.drop('WCIO Nature of Injury Code', axis=1, inplace=True)
X_test.drop('WCIO Nature of Injury Code', axis=1, inplace=True)

Scale the data:

In [144]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

## <span style="color:salmon"> 3. Logistic Regression </span> 

Applies Logistic Regression classifier:

In [145]:
model = LogisticRegression()

#### <span style="color:salmon"> 3.1 Fit the model to the train data </span> 

In [146]:
model.fit(X_train, y_train)

/opt/anaconda3/envs/ML2425/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

#### <span style="color:salmon"> 3.2 Predict the labels with model </span> 

Make training predictions:

In [147]:
y_train_pred = model.predict(X_train)

Make val predictions:

In [148]:
y_val_pred = model.predict(X_val)

Predict Probability in training

In [149]:
pred_prob = model.predict_proba(X_train)
pred_prob

array([[1.19909014e-03, 1.73301210e-02, 1.39469322e-01, ...,
        2.97051873e-02, 2.70659396e-04, 9.39723793e-04],
       [7.24166908e-03, 7.57400275e-01, 1.07226470e-01, ...,
        8.36087366e-06, 3.84560836e-06, 3.19175326e-05],
       [4.67488104e-03, 6.69027513e-02, 1.70026069e-01, ...,
        2.35663972e-02, 2.81820905e-04, 1.38765225e-04],
       ...,
       [1.73044403e-02, 2.48758550e-01, 3.24484936e-01, ...,
        2.60531821e-04, 1.60974084e-04, 6.82244005e-04],
       [9.32518692e-02, 2.50827041e-01, 2.67406731e-05, ...,
        7.19785096e-10, 5.90759734e-06, 1.78039891e-04],
       [3.67787917e-05, 1.88745965e-03, 1.06923059e-01, ...,
        4.41191321e-02, 6.77097240e-04, 1.92676896e-05]])

Predict Probability in val

In [150]:
pred_prob = model.predict_proba(X_val)
pred_prob

array([[8.48449670e-05, 1.06488386e-03, 8.83025836e-02, ...,
        1.67163160e-02, 3.14463309e-04, 7.35605838e-05],
       [1.16010163e-02, 6.87185574e-01, 1.18073091e-01, ...,
        1.80488924e-05, 1.41447127e-05, 8.27053957e-05],
       [1.26266246e-11, 5.15937187e-09, 1.07448126e-03, ...,
        9.20315410e-02, 2.83702421e-03, 9.44590416e-07],
       ...,
       [1.98758148e-02, 1.34600800e-01, 3.00742939e-01, ...,
        1.29125607e-02, 1.07876175e-04, 5.53315005e-05],
       [4.84777910e-01, 5.03793121e-01, 7.01157205e-03, ...,
        4.32884016e-08, 7.06674399e-07, 1.21320699e-07],
       [9.78999376e-03, 6.76490660e-01, 1.07649721e-01, ...,
        1.69099762e-05, 3.98385085e-06, 7.17710170e-06]])

In [151]:
model.coef_

array([[-1.39277718e-03, -4.00869277e-01,  4.43097173e-02,
        -2.23403870e+00,  1.67707297e-01,  0.00000000e+00,
         0.00000000e+00, -2.28920783e-01, -7.56986299e-02,
        -1.82518415e-01, -4.35639309e-02, -4.35639309e-02,
        -4.69690561e-01, -1.17327398e-01, -3.33947674e-02,
         5.98865408e-03,  4.36487198e-01,  1.59226865e-01,
         5.04656643e-03,  1.76682145e-02, -2.32063411e-01,
        -4.17184071e-02, -9.09830787e-03,  2.63665879e-02,
        -7.51131902e-02,  9.34553265e-02,  5.48390072e-03,
        -2.00255157e-02, -1.83466450e-01, -4.19327325e-02,
        -4.35586715e-03,  3.98348386e-03, -1.36081559e-01,
        -4.99854031e-02, -4.96232852e-03,  2.94498307e-02,
        -2.11039132e-02,  9.18198166e-02,  1.11494290e-01,
         2.36513397e-01, -2.28381775e-01, -3.81905438e-01,
        -9.71534579e-02,  6.44806712e-02,  6.84467151e-02,
         4.27830740e-02,  6.32959613e-02, -1.88018167e-02,
         1.58950253e-02, -1.08264616e-02,  1.97434433e-0

#### <span style="color:salmon"> 3.3 Evaluate the model </span> 

In [152]:
class_mapping = {
    0:'1. CANCELLED', 
    1:'2. NON-COMP',
    2:'3. MED ONLY', 
    3:'4. TEMPORARY',
    4:'5. PPD SCH LOSS', 
    5:'6. PPD NSL', 
    6:'7. PTD', 
    7:'8. DEATH'
}

# Use the values from class_mapping as the target names
target_names = list(class_mapping.values())

Compute confusion matrix to evaluate the accuracy of a classification

In [153]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_train, y_train_pred))
print("\nClassification Report:")
print(classification_report(y_train, y_train_pred, target_names=target_names))

Confusion Matrix:
[[  2125   6270     74    815     71      0      0      1]
 [  1511 205575    444   9900    867      1      0     11]
 [    87  34466   1091  13802   2230      1      0      3]
 [    86  43740   1199  62489   3851      2      2     11]
 [    17   4191    469  22214   9319      0      0      0]
 [     0     17     26   2735    380      0      0      0]
 [     1      0      1     61     10      0      0      0]
 [     0    170      6    148      5      0      0     23]]

Classification Report:
                 precision    recall  f1-score   support

   1. CANCELLED       0.56      0.23      0.32      9356
    2. NON-COMP       0.70      0.94      0.80    218309
    3. MED ONLY       0.33      0.02      0.04     51680
   4. TEMPORARY       0.56      0.56      0.56    111380
5. PPD SCH LOSS       0.56      0.26      0.35     36210
     6. PPD NSL       0.00      0.00      0.00      3158
         7. PTD       0.00      0.00      0.00        73
       8. DEATH       0.47  

In [154]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))
print("\nClassification Report:")
print(classification_report(y_val, y_val_pred, target_names=target_names))


Confusion Matrix:
[[  717  2083    19   265    35     0     0     0]
 [  495 68403   162  3352   351     0     0     6]
 [   22 11595   341  4538   729     0     1     0]
 [   27 14600   395 20805  1286     1     0    13]
 [    3  1388   179  7372  3126     1     0     1]
 [    0     5    14   876   158     0     0     0]
 [    0     0     0    19     5     0     0     0]
 [    0    48     3    55     4     0     0     8]]

Classification Report:
                 precision    recall  f1-score   support

   1. CANCELLED       0.57      0.23      0.33      3119
    2. NON-COMP       0.70      0.94      0.80     72769
    3. MED ONLY       0.31      0.02      0.04     17226
   4. TEMPORARY       0.56      0.56      0.56     37127
5. PPD SCH LOSS       0.55      0.26      0.35     12070
     6. PPD NSL       0.00      0.00      0.00      1053
         7. PTD       0.00      0.00      0.00        24
       8. DEATH       0.29      0.07      0.11       118

       accuracy                   

## <span style="color:salmon"> 4. Test Predictions </span> 

Make validation predictions:

In [ ]:
y_test_pred = model.predict(X_test)

In [ ]:
test_id = test_df.index

In [ ]:
submission_df = pd.DataFrame({
    'Claim Identifier': test_id,
    'Claim Injury Type': y_test_pred
})

In [ ]:
submission_df.to_csv('./submissions/Group49_logistic_model.csv', index=False)