# <center>Machine Learning Project</center>

** **
## <center>*03.4 - Instance Based*</center>

** **

The members of the `team` are:
- Ana Farinha - 20211514
- Francisco Capontes - 20211692
- Sofia Gomes - 20240848
- Rui Lourenço - 2021639



In [1]:
# Import libraries
import pandas as pd
import numpy as np

#make the split here
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.impute import KNNImputer

from utils import *

## <span style="color:salmon"> 1. Import Dataset </span> 

In [2]:
# Import dataset
df = pd.read_csv('preprocessed_data/train_data.csv', index_col="Claim Identifier")
df

Accident Date  Age at Injury  Average Weekly Wage  \
Claim Identifier                                                     
5393875             2019-12-30           31.0                  NaN   
5393091             2019-08-30           46.0              1745.93   
5393889             2019-12-06           40.0              1434.80   
5393887             2019-12-30           61.0                  NaN   
5393863             2019-12-26           67.0                  NaN   
...                        ...            ...                  ...   
6165265             2022-12-14           35.0                  NaN   
6165285             2022-12-15           33.0                  NaN   
6165506             2022-12-13           61.0               991.08   
6165339             2022-12-14           24.0                  NaN   
6165075             2022-12-13           72.0                  NaN   

                  Birth Year  IME-4 Count  Number of Dependents  \
Claim Identifier                                                  
5393875               1988.0          0.0                   1.0   
5393091               1973.0          4.0                   4.0   
5393889               1979.0          0.0                   6.0   
5393887               1958.0          0.0                   1.0   
5393863               1952.0          0.0                   5.0   
...                      ...          ...                   ...   
6165265               1987.0          0.0                   4.0   
6165285               1989.0          0.0                   6.0   
6165506               1961.0          1.0                   3.0   
6165339               1998.0          0.0                   5.0   
6165075               1950.0          0.0                   3.0   

                  Known Accident Date  Known Assembly Date  Known C-2 Date  \
Claim Identifier                                                             
5393875                             1                    1               1   
5393091                             1                    1               1   
5393889                             1                    1               1   
5393887                             1                    1               1   
5393863                             1                    1               1   
...                               ...                  ...             ...   
6165265                             1                    1               1   
6165285                             1                    1               1   
6165506                             1                    1               1   
6165339                             1                    1               1   
6165075                             1                    1               1   

                  Known C-3 Date  ...  Zip_Code_Hash_13  Zip_Code_Hash_14  \
Claim Identifier                  ...                                       
5393875                        0  ...               0.0               0.0   
5393091                        1  ...               0.0              -1.0   
5393889                        0  ...               0.0               0.0   
5393887                        0  ...               0.0               0.0   
5393863                        0  ...               0.0               0.0   
...                          ...  ...               ...               ...   
6165265                        0  ...               0.0               0.0   
6165285                        0  ...               0.0               0.0   
6165506                        0  ...               0.0               0.0   
6165339                        0  ...               0.0               0.0   
6165075                        0  ...               0.0               0.0   

                  Zip_Code_Hash_15  Zip_Code_Hash_16  Zip_Code_Hash_17  \
Claim Identifier                                                         
5393875                        0.0               0.0               0.

In [3]:
# Import dataset
test_df = pd.read_csv('./preprocessed_data/test_data.csv', index_col = 'Claim Identifier')
test_df

Accident Date  Age at Injury  Average Weekly Wage  \
Claim Identifier                                                     
6165911             2022-12-24           19.0                  NaN   
6166141             2022-11-20           19.0                  NaN   
6165907             2022-12-26           59.0                  NaN   
6166047             2022-12-28           55.0                  NaN   
6166102             2022-12-20           25.0                  NaN   
...                        ...            ...                  ...   
6553137             2012-09-12           52.0                  NaN   
6553119             2024-05-22           59.0                  NaN   
6553542             2024-05-06           45.0                  NaN   
6553455             2024-02-24           42.0                  NaN   
6553594             2024-06-05            NaN                  NaN   

                  Birth Year  IME-4 Count  Number of Dependents  \
Claim Identifier                                                  
6165911               2003.0          0.0                     1   
6166141               2003.0          0.0                     1   
6165907               1963.0          0.0                     0   
6166047               1967.0          0.0                     6   
6166102               1997.0          0.0                     5   
...                      ...          ...                   ...   
6553137               1960.0          0.0                     5   
6553119               1965.0          0.0                     1   
6553542               1979.0          0.0                     5   
6553455               1981.0          0.0                     5   
6553594                  NaN          0.0                     5   

                  Known Accident Date  Known Assembly Date  Known C-2 Date  \
Claim Identifier                                                             
6165911                             1                    1               1   
6166141                             1                    1               1   
6165907                             1                    1               1   
6166047                             1                    1               1   
6166102                             1                    1               1   
...                               ...                  ...             ...   
6553137                             1                    1               1   
6553119                             1                    1               0   
6553542                             1                    1               0   
6553455                             1                    1               0   
6553594                             1                    1               0   

                  Known C-3 Date  ...  Zip_Code_Hash_12  Zip_Code_Hash_13  \
Claim Identifier                  ...                                       
6165911                        0  ...               0.0               0.0   
6166141                        0  ...               0.0               0.0   
6165907                        0  ...               0.0               0.0   
6166047                        0  ...               0.0              -1.0   
6166102                        0  ...               0.0               0.0   
...                          ...  ...               ...               ...   
6553137                        0  ...               0.0               0.0   
6553119                        1  ...               0.0               0.0   
6553542                        0  ...               0.0               0.0   
6553455                        1  ...               0.0               0.0   
6553594                        1  ...               0.0               0.0   

                  Zip_Code_Hash_14  Zip_Code_Hash_15  Zip_Code_Hash_16  \
Claim Identifier                                                         
6165911                        0.0               0.0               0.

## <span style="color:salmon"> 2. Prepare Dataset </span> 

Define y as a target "Claim Injury Type Encoded" and X with all the other columns

In [4]:
X = df.drop(["Claim Injury Type Encoded"], axis = 1)
y = df["Claim Injury Type Encoded"]

Split the data and the target to X_train, X_test, y_train, y_test, where test_size should be equal to 0.25, stratify equal to target and shuffle equal to True

In [5]:
X_train, X_val, y_train, y_val = train_test_split(X,y, test_size = 0.25, stratify = y, shuffle = True)

Define X_test

In [6]:
X_test = test_df.copy()

Check missing values in each dataset:

In [7]:
X_train.isna().sum().sort_values()[X_train.isna().sum() != 0]

Birth Year               1633
Age at Injury            1633
Average Weekly Wage    272935
dtype: int64

In [8]:
X_val.isna().sum().sort_values()[X_val.isna().sum() != 0]

Birth Year               553
Age at Injury            553
Average Weekly Wage    91164
dtype: int64

In [9]:
X_test.isna().sum().sort_values()[X_test.isna().sum() != 0]

Birth Year                982
Age at Injury             982
Average Weekly Wage    335753
dtype: int64

Input `Average Weekly Wage` and variables created from it

In [10]:
median_avg_week_wage = X_train['Average Weekly Wage'].median()

X_train['Average Weekly Wage'] = X_train['Average Weekly Wage'].fillna(median_avg_week_wage)
X_val['Average Weekly Wage'] = X_val['Average Weekly Wage'].fillna(median_avg_week_wage)
X_test['Average Weekly Wage'] = X_test['Average Weekly Wage'].fillna(median_avg_week_wage)

In [11]:
financial_impact(X_train)
financial_impact(X_val)
financial_impact(X_test)

*Input `Age at Injury` and variables that can be calculated with it*

In [12]:
median_age_at_injury = X_train['Age at Injury'].median()

X_train['Age at Injury'] = X_train['Age at Injury'].fillna(median_age_at_injury)
X_val['Age at Injury'] = X_val['Age at Injury'].fillna(median_age_at_injury)
X_test['Age at Injury'] = X_test['Age at Injury'].fillna(median_age_at_injury)

In [13]:
def calculate_birth_year(df):
    # Ensure the correct format of 'Birth Year'
    df['Accident Date'] = pd.to_datetime(df['Accident Date'], errors='coerce')

    # Filter the rows where 'Birth Year' is NaN, but 'Age at Injury' and 'Accident Date' are not NaN
    condition = df['Birth Year'].isna() & df['Age at Injury'].notna() & df['Accident Date'].notna()

    # Replace missing 'Birth Year' with the difference between 'Accident Date' year and 'Age at Injury'
    df.loc[condition, 'Birth Year'] = df.loc[condition, 'Accident Date'].dt.year - df.loc[condition, 'Age at Injury']

In [14]:
calculate_birth_year(X_train)
calculate_birth_year(X_val)
calculate_birth_year(X_test)

Drop the columns: Accident Date

In [15]:
X_train.drop('Accident Date', axis=1, inplace=True)
X_val.drop('Accident Date', axis=1, inplace=True)
X_test.drop('Accident Date', axis=1, inplace=True)

In [16]:
class_mapping = {
    0:'1. CANCELLED', 
    1:'2. NON-COMP',
    2:'3. MED ONLY', 
    3:'4. TEMPORARY',
    4:'5. PPD SCH LOSS', 
    5:'6. PPD NSL', 
    6:'7. PTD', 
    7:'8. DEATH'
}

# Use the values from class_mapping as the target names
target_names = list(class_mapping.values())

## <span style="color:salmon"> 3. Instance Based </span> 

In [17]:
model_KNN_N = KNeighborsClassifier(n_neighbors=11).fit(X_train, y_train)

In [18]:
y_train_pred = model_KNN_N.predict(X_train)
y_val_pred = model_KNN_N.predict(X_val)
y_val_pred

array([1, 1, 1, ..., 1, 0, 1])

In [19]:
print(model_KNN_N.score(X_train, y_train))
print(model_KNN_N.score(X_val, y_val))

0.7684045730956661
0.7481220297409168


In [20]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_train, y_train_pred))
print("\nClassification Report:")
print(classification_report(y_train, y_train_pred, target_names=target_names))

Confusion Matrix:
[[  3234   5635    208    270      9      0      0      0]
 [  1547 213783   1251   1625    101      1      0      0]
 [    94  27912   5235  16636   1798      2      0      3]
 [   103   8565   2739  95917   4049      1      0      6]
 [    17   1481   1335  20747  12624      1      0      5]
 [     3     87    145   2509    410      3      0      1]
 [     1      4      5     54      9      0      0      0]
 [     2     83     32    208     12      0      0     16]]

Classification Report:


/opt/anaconda3/envs/ML2425/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/envs/ML2425/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


                 precision    recall  f1-score   support

   1. CANCELLED       0.65      0.35      0.45      9356
    2. NON-COMP       0.83      0.98      0.90    218308
    3. MED ONLY       0.48      0.10      0.17     51680
   4. TEMPORARY       0.70      0.86      0.77    111380
5. PPD SCH LOSS       0.66      0.35      0.46     36210
     6. PPD NSL       0.38      0.00      0.00      3158
         7. PTD       0.00      0.00      0.00        73
       8. DEATH       0.52      0.05      0.08       353

       accuracy                           0.77    430518
      macro avg       0.53      0.34      0.35    430518
   weighted avg       0.73      0.77      0.72    430518



/opt/anaconda3/envs/ML2425/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [21]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))
print("\nClassification Report:")
print(classification_report(y_val, y_val_pred, target_names=target_names))

Confusion Matrix:
[[  915  2024    78   100     2     0     0     0]
 [  709 70811   577   637    35     1     0     0]
 [   36  9540  1162  5815   673     0     0     0]
 [   35  3027  1316 30866  1879     1     0     3]
 [   13   534   512  7406  3604     0     0     1]
 [    0    29    52   856   116     0     0     0]
 [    0     0     0    18     6     0     0     0]
 [    3    27     9    73     3     0     0     2]]

Classification Report:


/opt/anaconda3/envs/ML2425/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


                 precision    recall  f1-score   support

   1. CANCELLED       0.53      0.29      0.38      3119
    2. NON-COMP       0.82      0.97      0.89     72770
    3. MED ONLY       0.31      0.07      0.11     17226
   4. TEMPORARY       0.67      0.83      0.74     37127
5. PPD SCH LOSS       0.57      0.30      0.39     12070
     6. PPD NSL       0.00      0.00      0.00      1053
         7. PTD       0.00      0.00      0.00        24
       8. DEATH       0.33      0.02      0.03       117

       accuracy                           0.75    143506
      macro avg       0.41      0.31      0.32    143506
   weighted avg       0.69      0.75      0.70    143506



/opt/anaconda3/envs/ML2425/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/envs/ML2425/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


## <span style="color:salmon"> 4. Test predictions </span> 

Make validation predictions:

In [22]:
y_test_pred = model_KNN_N.predict(X_test)

In [23]:
test_id = test_df.index

In [24]:
submission_df = pd.DataFrame({
    'Claim Identifier': test_id,
    'Claim Injury Type': y_test_pred
})