# <center>Machine Learning Project</center>

** **
## <center>*03 - Base Model Notebook*</center>

** **

Description of the notebook

Simple Model with evaluation


The members of the `team` are:
- Ana Farinha - 20211514
- Francisco Capontes - 20211692
- Sofia Gomes - 20240848
- Rui Lourenço - 2021639

In [1]:
# Import libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
# Import dataset
df = pd.read_csv('./project_data/train_data.csv', index_col = 'Claim Identifier')
df

C:\Users\Utilizador\AppData\Local\Temp\ipykernel_1904\4090981752.py:2: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('./project_data/train_data.csv', index_col = 'Claim Identifier')


Accident Date  Age at Injury Alternative Dispute Resolution  \
Claim Identifier                                                               
5393875             2019-12-30           31.0                              N   
5393091             2019-08-30           46.0                              N   
5393889             2019-12-06           40.0                              N   
957648180                  NaN            NaN                            NaN   
5393887             2019-12-30           61.0                              N   
...                        ...            ...                            ...   
327160035                  NaN            NaN                            NaN   
6165075             2022-12-13           72.0                              N   
249875936                  NaN            NaN                            NaN   
120584215                  NaN            NaN                            NaN   
818961390                  NaN            NaN                            NaN   

                 Assembly Date Attorney/Representative  Average Weekly Wage  \
Claim Identifier                                                              
5393875             2020-01-01                       N                 0.00   
5393091             2020-01-01                       Y              1745.93   
5393889             2020-01-01                       N              1434.80   
957648180           2020-01-01                     NaN                  NaN   
5393887             2020-01-01                       N                  NaN   
...                        ...                     ...                  ...   
327160035           2022-12-31                     NaN                  NaN   
6165075             2022-12-31                       N                 0.00   
249875936           2022-12-31                     NaN                  NaN   
120584215           2022-12-31                     NaN                  NaN   
818961390           2022-12-31                     NaN                  NaN   

                  Birth Year    C-2 Date    C-3 Date  \
Claim Identifier                                       
5393875               1988.0  2019-12-31         NaN   
5393091               1973.0  2020-01-01  2020-01-14   
5393889               1979.0  2020-01-01         NaN   
957648180                NaN         NaN         NaN   
5393887               1958.0  2019-12-31         NaN   
...                      ...         ...         ...   
327160035                NaN         NaN         NaN   
6165075               1950.0  2022-12-31         NaN   
249875936                NaN         NaN         NaN   
120584215                NaN         NaN         NaN   
818961390                NaN         NaN         NaN   

                                   Carrier Name  ...  \
Claim Identifier                                 ...   
5393875              NEW HAMPSHIRE INSURANCE CO  ...   
5393091            ZURICH AMERICAN INSURANCE CO  ...   
5393889               INDEMNITY INSURANCE CO OF  ...   
957648180                                   NaN  ...   
5393887                    STATE INSURANCE FUND  ...   
...                                         ...  ...   
327160035                                   NaN  ...   
6165075           TECHNOLOGY INSURANCE CO. INC.  ...   
249875936                                   NaN  ...   
120584215                                   NaN  ...   
818961390                                   NaN  ...   

                 WCIO Cause of Injury Code  WCIO Cause of Injury Description  \
Claim Identifier                                                               
5393875                               27.0      FROM LIQUID OR GREASE SPILLS   
5393091                               97.0                 REPETITIVE MOTION   
5393889                               79.0    OBJECT BEING LIFTED OR HANDLED   
957648180                              NaN                               NaN   
5393887   

In [3]:
# Remove the na to make the visualization possible
df = df.dropna(subset=['Claim Injury Type'])

In [4]:
# Encode the target variable
label_encoder = LabelEncoder()
df['Claim Injury Type Encoded'] = label_encoder.fit_transform(df['Claim Injury Type'])

C:\Users\Utilizador\AppData\Local\Temp\ipykernel_1904\1942064479.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Claim Injury Type Encoded'] = label_encoder.fit_transform(df['Claim Injury Type'])


In [5]:
# Define features and target
X = df[['Age at Injury', 'Average Weekly Wage', 'Birth Year', 'IME-4 Count', 'Industry Code', 'WCIO Cause of Injury Code', 'WCIO Nature of Injury Code','WCIO Part Of Body Code', 'Number of Dependents']]
y = df['Claim Injury Type Encoded']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
# Initialize and train the Random Forest classifier
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))


Confusion Matrix:
[[  768  1588    56    39     1     0     0     0]
 [  626 56286  1024   458    24     0     0     0]
 [   18  7679   709  4783   559     1     0     0]
 [   21  1867   562 25287  1935     7     0     3]
 [    1   116    95  4875  4496     2     0     0]
 [    0     3     7   708    95     2     0     0]
 [    0     0     0    13     1     0     0     0]
 [    0    16     4    68     1     0     0     2]]

Classification Report:
                 precision    recall  f1-score   support

   1. CANCELLED       0.54      0.31      0.40      2452
    2. NON-COMP       0.83      0.96      0.89     58418
    3. MED ONLY       0.29      0.05      0.09     13749
   4. TEMPORARY       0.70      0.85      0.77     29682
5. PPD SCH LOSS       0.63      0.47      0.54      9585
     6. PPD NSL       0.17      0.00      0.00       815
         7. PTD       0.00      0.00      0.00        14
       8. DEATH       0.40      0.02      0.04        91

       accuracy                   

c:\Users\Utilizador\anaconda3\envs\ML_Project\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Utilizador\anaconda3\envs\ML_Project\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Utilizador\anaconda3\envs\ML_Project\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitaliz

In [7]:
# Import dataset
test_df = pd.read_csv('./project_data/test_data.csv', index_col = 'Claim Identifier')
test_df

Accident Date  Age at Injury Alternative Dispute Resolution  \
Claim Identifier                                                               
6165911             2022-12-24             19                              N   
6166141             2022-11-20             19                              N   
6165907             2022-12-26             59                              N   
6166047             2022-12-28             55                              N   
6166102             2022-12-20             25                              N   
...                        ...            ...                            ...   
6553137             2012-09-12             52                              N   
6553119             2024-05-22             59                              N   
6553542             2024-05-06             45                              N   
6553455             2024-02-24             42                              N   
6553594                    NaN              0                              N   

                 Assembly Date Attorney/Representative  Average Weekly Wage  \
Claim Identifier                                                              
6165911             2023-01-02                       N                  NaN   
6166141             2023-01-02                       N                  NaN   
6165907             2023-01-02                       N                  0.0   
6166047             2023-01-02                       N                  0.0   
6166102             2023-01-02                       N                  0.0   
...                        ...                     ...                  ...   
6553137             2024-06-05                       N                  NaN   
6553119             2024-06-05                       Y                  0.0   
6553542             2024-06-05                       Y                  0.0   
6553455             2024-06-05                       Y                  0.0   
6553594             2024-06-05                       Y                  0.0   

                  Birth Year    C-2 Date    C-3 Date  \
Claim Identifier                                       
6165911               2003.0  2023-01-02         NaN   
6166141               2003.0  2023-01-02         NaN   
6165907               1963.0  2022-12-31         NaN   
6166047                  0.0  2023-01-02         NaN   
6166102               1997.0  2022-12-31         NaN   
...                      ...         ...         ...   
6553137               1960.0  2012-10-23         NaN   
6553119               1965.0         NaN  2024-05-28   
6553542               1979.0         NaN         NaN   
6553455               1981.0         NaN  2024-05-21   
6553594                  NaN         NaN  2024-05-28   

                                   Carrier Name  ... Medical Fee Region  \
Claim Identifier                                 ...                      
6165911               INDEMNITY INSURANCE CO OF  ...                 IV   
6166141                 A I U INSURANCE COMPANY  ...                 IV   
6165907               AMGUARD INSURANCE COMPANY  ...                III   
6166047             INDEMNITY INS. OF N AMERICA  ...                 IV   
6166102              NEW HAMPSHIRE INSURANCE CO  ...                 IV   
...                                         ...  ...                ...   
6553137                    STATE INSURANCE FUND  ...                  I   
6553119                   NYC TRANSIT AUTHORITY  ...                 IV   
6553542                    STATE INSURANCE FUND  ...                 IV   
6553455           NEW YORK BLACK CAR OPERATORS'  ...                 IV   
6553594            CNY OTHER THAN ED, HED WATER  ...                 IV   

                 OIICS Nature of Injury Description WCIO Cause of Injury Code  \
Claim Identifier                                                                
6165911                                         NaN                      31.0   


In [8]:
# Make predictions
y_pred = model.predict(test_df[['Age at Injury', 'Average Weekly Wage', 'Birth Year', 'IME-4 Count', 'Industry Code', 'WCIO Cause of Injury Code', 'WCIO Nature of Injury Code','WCIO Part Of Body Code', 'Number of Dependents']])

In [9]:
y_pred = label_encoder.inverse_transform(y_pred)

In [12]:
test_id = test_df.index

In [13]:
submission_df = pd.DataFrame({
    'Claim Identifier': test_id,
    'Claim Injury Type': y_pred
})

In [15]:
# Save the DataFrame to a CSV file
submission_df.to_csv('./submissions/Group49_Version01.csv', index=False)